# ============================================
# LOKI CONFIGURATION
# ============================================
# Agrégation des logs de tous les containers Docker
# Rétention: 7 jours
# Compatible avec Loki 2.9+
# ============================================

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

# Schema configuration - Using TSDB for better performance
schema_config:
  configs:
    - from: 2023-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

# Storage configuration
storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-shipper-active
    cache_location: /loki/tsdb-shipper-cache
    cache_ttl: 24h
  filesystem:
    directory: /loki/chunks

# Limits configuration
limits_config:
  # Limites de rétention
  retention_period: 168h  # 7 jours

  # Limites de taille
  max_query_length: 721h
  max_query_lookback: 168h
  max_streams_per_user: 10000
  max_global_streams_per_user: 50000

  # Limites de taux (pour économiser la RAM)
  ingestion_rate_mb: 4
  ingestion_burst_size_mb: 6
  max_entries_limit_per_query: 5000
  max_chunks_per_query: 2000000

  # Rejet des logs trop anciens
  reject_old_samples: true
  reject_old_samples_max_age: 168h

# Compactor configuration (for retention and cleanup)
compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: filesystem
