# Configuration des Intentions Harena - Version Autonome  
# Version: 2.0.0
# Date: 2025-01-XX
# Approche: Few-shot learning pour classification autonome

metadata:
  version: "2.0.0"
  description: "Configuration allégée pour classification autonome des intentions"
  approach: "few_shot_autonomous_classification"
  last_updated: "2025-01-XX"

# ============================================================================
# GROUPES D'INTENTIONS PRINCIPAUX
# ============================================================================
intent_groups:
  
  # ========================================================================
  # GROUPE 1: RECHERCHE ET CONSULTATION DE TRANSACTIONS
  # ========================================================================
  TRANSACTION_SEARCH:
    description: "Recherche et consultation de transactions"
    priority: 1
    
    patterns_generiques:
      search_by_criteria:
        description: "Recherche par critères variés"
        few_shot_examples:
          - input: "mes transactions du mois de mai"
            output: {
              "intent_group": "TRANSACTION_SEARCH",
              "intent_subtype": "by_date", 
              "entities": {"periode_temporelle": "2024-05-01 to 2024-05-31"},
              "query_strategy": "date_filter"
            }
          
          - input: "mes achats chez Amazon"
            output: {
              "intent_group": "TRANSACTION_SEARCH",
              "intent_subtype": "by_merchant",
              "entities": {"merchant_name": "Amazon"},
              "query_strategy": "merchant_search"
            }
          
          - input: "transactions supérieures à 100 euros"
            output: {
              "intent_group": "TRANSACTION_SEARCH", 
              "intent_subtype": "by_amount",
              "entities": {"montant": {"gte": 100}},
              "query_strategy": "amount_filter"
            }
          
          - input: "mes dépenses alimentaires ce mois"
            output: {
              "intent_group": "TRANSACTION_SEARCH",
              "intent_subtype": "by_category_and_date",
              "entities": {
                "category_search": "food alimentation",
                "periode_temporelle": "current_month"
              },
              "query_strategy": "composite_filter"
            }

      search_complexity_guidance:
        - "Identifier si recherche simple (1 critère) ou composite (plusieurs critères)"
        - "Mapper les termes naturels vers champs search_service appropriés"
        - "Privilégier recherche textuelle pour flexibilité"
        - "Combiner filtres structurés et recherche libre selon contexte"

  # ========================================================================
  # GROUPE 2: ANALYSES ET INSIGHTS
  # ========================================================================
  ANALYSIS_INSIGHTS:
    description: "Analyses et insights sur les données financières"
    priority: 2
    
    patterns_generiques:
      spending_analysis:
        description: "Analyses de dépenses diverses"
        few_shot_examples:
          - input: "combien j'ai dépensé ce mois ?"
            output: {
              "intent_group": "ANALYSIS_INSIGHTS",
              "intent_subtype": "spending_total",
              "entities": {"periode_temporelle": "current_month"},
              "query_strategy": "sum_aggregation"
            }
          
          - input: "répartition de mes dépenses par catégorie"
            output: {
              "intent_group": "ANALYSIS_INSIGHTS",
              "intent_subtype": "spending_breakdown", 
              "entities": {"dimension_analyse": "category"},
              "query_strategy": "terms_aggregation"
            }
          
          - input: "évolution de mes dépenses sur 6 mois"
            output: {
              "intent_group": "ANALYSIS_INSIGHTS",
              "intent_subtype": "spending_trend",
              "entities": {
                "periode_analyse": "last_6_months",
                "granularite": "monthly"
              },
              "query_strategy": "date_histogram_aggregation"
            }
          
          - input: "comparer mai vs avril"
            output: {
              "intent_group": "ANALYSIS_INSIGHTS",
              "intent_subtype": "period_comparison",
              "entities": {
                "periode_1": "2024-05-01 to 2024-05-31",
                "periode_2": "2024-04-01 to 2024-04-30"
              },
              "query_strategy": "multi_period_analysis"
            }

      analysis_complexity_guidance:
        - "Distinguer analyses simples (totaux) vs complexes (comparaisons)"
        - "Identifier le niveau d'agrégation demandé (jour/mois/année)"
        - "Détecter les demandes de comparaison temporelle ou catégorielle"
        - "Adapter la granularité selon la période analysée"

  # ========================================================================
  # GROUPE 3: CONSULTATION SOLDES ET COMPTES
  # ========================================================================
  ACCOUNT_BALANCE:
    description: "Consultation des soldes et informations de comptes"
    priority: 3
    
    patterns_generiques:
      balance_inquiry:
        description: "Consultation de soldes"
        few_shot_examples:
          - input: "quel est mon solde ?"
            output: {
              "intent_group": "ACCOUNT_BALANCE",
              "intent_subtype": "current_balance",
              "entities": {},
              "query_strategy": "account_balance_all"
            }
          
          - input: "solde de mon compte courant"
            output: {
              "intent_group": "ACCOUNT_BALANCE", 
              "intent_subtype": "balance_by_type",
              "entities": {"account_type": "checking"},
              "query_strategy": "account_balance_filtered"
            }
          
          - input: "évolution de mon solde ce mois"
            output: {
              "intent_group": "ACCOUNT_BALANCE",
              "intent_subtype": "balance_evolution",
              "entities": {"periode_temporelle": "current_month"},
              "query_strategy": "balance_history_analysis"
            }

      balance_guidance:
        - "Distinguer solde actuel vs historique"
        - "Identifier si demande spécifique à un compte ou globale"
        - "Détecter les demandes d'évolution temporelle"

  # ========================================================================
  # GROUPE 4: INTERACTIONS CONVERSATIONNELLES
  # ========================================================================
  CONVERSATIONAL:
    description: "Interactions sociales et conversationnelles"
    priority: 4
    
    patterns_generiques:
      social_interaction:
        description: "Interactions sociales de base"
        few_shot_examples:
          - input: "bonjour"
            output: {
              "intent_group": "CONVERSATIONAL",
              "intent_subtype": "greeting",
              "entities": {},
              "query_strategy": "no_search_needed"
            }
          
          - input: "merci c'est parfait"
            output: {
              "intent_group": "CONVERSATIONAL",
              "intent_subtype": "gratitude", 
              "entities": {},
              "query_strategy": "no_search_needed"
            }

      context_reference:
        description: "Références au contexte conversationnel"
        few_shot_examples:
          - input: "et pour avril ?"
            output: {
              "intent_group": "CONVERSATIONAL",
              "intent_subtype": "context_continuation",
              "entities": {"reference_contextuelle": "modify_period", "nouveau_parametre": "april"},
              "query_strategy": "modify_previous_query"
            }
          
          - input: "pareil pour Amazon"
            output: {
              "intent_group": "CONVERSATIONAL", 
              "intent_subtype": "context_continuation",
              "entities": {"reference_contextuelle": "modify_merchant", "nouveau_parametre": "Amazon"},
              "query_strategy": "modify_previous_query"
            }

      conversational_guidance:
        - "Identifier les références au contexte précédent"
        - "Distinguer interactions sociales vs demandes de modification"
        - "Préserver l'intention de base tout en modifiant les paramètres"

  # ========================================================================
  # GROUPE 5: GESTION SYSTÈME ET AIDE
  # ========================================================================
  SYSTEM_CONTROL:
    description: "Contrôle système, aide et gestion des erreurs"
    priority: 5
    
    patterns_generiques:
      help_requests:
        description: "Demandes d'aide et support"
        few_shot_examples:
          - input: "aide"
            output: {
              "intent_group": "SYSTEM_CONTROL",
              "intent_subtype": "general_help",
              "entities": {},
              "query_strategy": "show_capabilities"
            }
          
          - input: "comment chercher mes transactions ?"
            output: {
              "intent_group": "SYSTEM_CONTROL",
              "intent_subtype": "feature_help",
              "entities": {"fonctionnalite": "transactions"},
              "query_strategy": "explain_feature"
            }

      error_handling:
        description: "Gestion des cas d'erreur et ambiguïtés"
        few_shot_examples:
          - input: "je ne sais pas quoi chercher"
            output: {
              "intent_group": "SYSTEM_CONTROL",
              "intent_subtype": "unclear_intent",
              "entities": {},
              "query_strategy": "request_clarification"
            }
          
          - input: "fais-moi un virement"
            output: {
              "intent_group": "SYSTEM_CONTROL",
              "intent_subtype": "out_of_scope",
              "entities": {},
              "query_strategy": "explain_limitations"
            }

      system_guidance:
        - "Identifier les demandes hors périmètre" 
        - "Distinguer aide générale vs aide spécifique"
        - "Gérer les intentions ambiguës avec bienveillance"

# ============================================================================
# STRATÉGIES DE CLASSIFICATION AUTONOME
# ============================================================================
classification_strategies:
  autonomous_approach:
    description: "Principes pour classification autonome par LLM"
    
    core_principles:
      - "Utiliser le contexte naturel plutôt que des règles rigides"
      - "Permettre des intentions composites et créatives"
      - "S'adapter aux variations linguistiques naturelles"
      - "Apprendre de nouveaux patterns non prévus"
    
    pattern_recognition:
      - "Identifier les mots-clés financiers ('dépenses', 'solde', 'achats')"
      - "Détecter les expressions temporelles variées"
      - "Reconnaître les noms de marchands sans liste prédéfinie"
      - "Comprendre les demandes d'analyse implicites"
    
    context_awareness:
      - "Tenir compte de l'historique conversationnel"
      - "Adapter l'intention selon le contexte utilisateur"
      - "Gérer les références pronominales ('ça', 'la même chose')"
      - "Maintenir la cohérence dans une session"

  confidence_scoring:
    description: "Évaluation de confiance sans seuils rigides"
    
    factors:
      - "Clarté de l'expression utilisateur"
      - "Présence d'entités financières identifiables"
      - "Cohérence avec le contexte précédent"
      - "Complexité de la demande"
    
    adaptive_thresholds:
      - "Seuils flexibles selon le contexte"
      - "Apprentissage des patterns de confiance"
      - "Dégradation gracieuse en cas d'incertitude"

# ============================================================================
# MAPPING VERS STRATÉGIES DE REQUÊTE
# ============================================================================
query_strategies:
  description: "Stratégies de génération de requêtes search_service"
  
  simple_strategies:
    date_filter:
      target_fields: ["date"]
      query_pattern: "filter_based"
    
    merchant_search:
      target_fields: ["merchant_name", "query"] 
      query_pattern: "text_search"
    
    amount_filter:
      target_fields: ["amount_abs"]
      query_pattern: "range_filter"
    
    category_search:
      target_fields: ["category_name", "query"]
      query_pattern: "text_search"
  
  aggregation_strategies:
    sum_aggregation:
      aggregation_type: "sum"
      target_field: "amount_abs"
    
    terms_aggregation:
      aggregation_type: "terms"
      target_fields: ["category_name.keyword", "merchant_name.keyword"]
    
    date_histogram_aggregation:
      aggregation_type: "date_histogram"
      target_field: "date"
      intervals: ["1d", "1w", "1M", "quarter"]
  
  composite_strategies:
    multi_filter:
      description: "Combinaison de plusieurs filtres"
      flexibility: "high"
    
    multi_period_analysis:
      description: "Analyses comparatives entre périodes" 
      complexity: "advanced"

# ============================================================================
# MÉCANISMES D'APPRENTISSAGE
# ============================================================================
learning_mechanisms:
  pattern_discovery:
    description: "Découverte automatique de nouveaux patterns"
    enabled: true
    
    methods:
      - "Analyse des requêtes non classifiées"
      - "Détection de patterns émergents"
      - "Feedback utilisateur pour amélioration"
      - "Adaptation aux domaines métiers spécifiques"
  
  continuous_improvement:
    description: "Amélioration continue du système"
    
    feedback_loops:
      - "Performance des requêtes générées"
      - "Satisfaction utilisateur sur les réponses"
      - "Taux de reformulation des questions"
      - "Précision des classifications"

# ============================================================================
# CONFIGURATION GLOBALE
# ============================================================================
global_settings:
  classification_approach: "autonomous_llm_with_few_shot"
  learning_enabled: true
  context_awareness: true
  pattern_flexibility: "high"
  
validation_approach:
  rule: "validate_output_structure_only"
  description: "Valider uniquement la structure JSON, pas le contenu"
  
output_format:
  required_fields: ["intent_group", "intent_subtype", "entities", "query_strategy"]
  flexible_entities: true
  allow_creative_intentions: true

performance_settings:
  cache_classifications: true
  adaptive_confidence: true
  context_window: 10  # Garder 10 échanges pour contexte riche