from .entity_extraction_prompts import ENTITY_EXTRACTION_SYSTEM_MESSAGE
from .few_shot_examples import ENTITY_EXTRACTION_FEW_SHOT_EXAMPLES

__all__ = [
    "ENTITY_EXTRACTION_SYSTEM_MESSAGE",
    "ENTITY_EXTRACTION_FEW_SHOT_EXAMPLES",
]

