"""cleanup_conversation_tables_final

Revision ID: a58a4daacbb8
Revises: 5bca1761167c
Create Date: 2025-09-02 06:28:59.185874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a58a4daacbb8'
down_revision: Union[str, None] = '5bca1761167c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.drop_index('ix_conversation_turns_intent_type')
        batch_op.drop_index('ix_conversation_turns_request_id')
        batch_op.drop_column('processing_time_ms')
        batch_op.drop_column('intent_type')
        batch_op.drop_column('request_id')
        batch_op.drop_column('quality_score')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality_score', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('intent_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('processing_time_ms', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_index('ix_conversation_turns_request_id', ['request_id'], unique=False)
        batch_op.create_index('ix_conversation_turns_intent_type', ['intent_type'], unique=False)

    # ### end Alembic commands ###
