"""enhance conversation for ai

Revision ID: 12d193f2a3ae
Revises: 4f2079db2694
Create Date: 2025-08-22 10:55:00.607115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d193f2a3ae'
down_revision: Union[str, None] = '4f2079db2694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intent', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('entities', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('prompt_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completion_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_tokens', sa.Integer(), nullable=True))

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intents', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('entities', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('prompt_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completion_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_tokens', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('total_tokens')
        batch_op.drop_column('completion_tokens')
        batch_op.drop_column('prompt_tokens')
        batch_op.drop_column('entities')
        batch_op.drop_column('intents')

    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.drop_column('total_tokens')
        batch_op.drop_column('completion_tokens')
        batch_op.drop_column('prompt_tokens')
        batch_op.drop_column('entities')
        batch_op.drop_column('intent')

    # ### end Alembic commands ###
