"""Modif conversation_service pour utiliser uniquement LLM

Revision ID: 44775ef78f2d
Revises: 93f0d886307b
Create Date: 2025-08-14 10:10:32.496646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44775ef78f2d'
down_revision: Union[str, None] = '93f0d886307b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intent_result', sa.JSON(), nullable=True))
        batch_op.drop_index('ix_conversation_turns_intent_detected')
        batch_op.drop_column('entities_extracted')
        batch_op.drop_column('intent_detected')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intent_detected', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('entities_extracted', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.create_index('ix_conversation_turns_intent_detected', ['intent_detected'], unique=False)
        batch_op.drop_column('intent_result')

    # ### end Alembic commands ###
