"""enrich conversation_turns

Revision ID: 48f2e3ebd17c
Revises: 89cf29c22f13
Create Date: 2025-08-23 21:16:49.840817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f2e3ebd17c'
down_revision: Union[str, None] = '89cf29c22f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('financial_context', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('user_preferences_ai', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('key_entities_history', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('openai_usage_stats', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('openai_cost_usd', sa.Float(), nullable=False))
        batch_op.alter_column('intent_confidence',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=False)
        batch_op.alter_column('total_tokens_used',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('db_query_time_ms')
        batch_op.drop_column('openai_cost')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('financial_context', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('user_preferences_ai', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('key_entities_history', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('intent_classification', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('entities_extracted', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('intent_confidence', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('total_tokens_used', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('openai_usage_stats', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('openai_cost_usd', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('openai_cost_usd')
        batch_op.drop_column('openai_usage_stats')
        batch_op.drop_column('total_tokens_used')
        batch_op.drop_column('intent_confidence')
        batch_op.drop_column('entities_extracted')
        batch_op.drop_column('intent_classification')
        batch_op.drop_column('key_entities_history')
        batch_op.drop_column('user_preferences_ai')
        batch_op.drop_column('financial_context')

    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openai_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('db_query_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.alter_column('total_tokens_used',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('intent_confidence',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=True)
        batch_op.drop_column('openai_cost_usd')
        batch_op.drop_column('openai_usage_stats')
        batch_op.drop_column('key_entities_history')
        batch_op.drop_column('user_preferences_ai')
        batch_op.drop_column('financial_context')

    # ### end Alembic commands ###
