"""change_bridge_transaction_id_to_bigint

Revision ID: 87a774709f3b
Revises: 5d46fac7c95d
Create Date: 2025-05-10 08:13:08.657265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a774709f3b'
down_revision: Union[str, None] = '5d46fac7c95d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_transactions', schema=None) as batch_op:
        batch_op.alter_column('bridge_transaction_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_transactions', schema=None) as batch_op:
        batch_op.alter_column('bridge_transaction_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
