# ============================================
# PROMETHEUS CONFIGURATION
# ============================================
# Collecte des métriques pour tous les services Harena
# Rétention: 7 jours
# ============================================

global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

  external_labels:
    cluster: 'harena-production'
    environment: 'aws-ec2'

# Alerting configuration (optionnel - pour plus tard)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Rule files for alerting
rule_files:
  # - "alerts/*.yml"

scrape_configs:
  # ============================================
  # PROMETHEUS SELF-MONITORING
  # ============================================
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
          type: 'monitoring'

  # ============================================
  # SYSTEM METRICS - NODE EXPORTER
  # ============================================
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          service: 'node-exporter'
          type: 'system'
          instance: 'ec2-harena'

  # ============================================
  # DOCKER METRICS - CADVISOR
  # ============================================
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'cadvisor'
          type: 'containers'
          instance: 'ec2-harena'

  # ============================================
  # APPLICATION SERVICES (via Blackbox Exporter)
  # ============================================

  # User Service
  - job_name: 'user_service'
    metrics_path: /probe
    params:
      module: [http_health_check]
    static_configs:
      - targets:
        - http://user_service:3000/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
      - target_label: service
        replacement: 'user_service'
      - target_label: type
        replacement: 'backend'
      - target_label: api_version
        replacement: 'v1'
    scrape_interval: 30s

  # Search Service
  - job_name: 'search_service'
    metrics_path: /probe
    params:
      module: [http_health_check]
    static_configs:
      - targets:
        - http://search_service:3001/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
      - target_label: service
        replacement: 'search_service'
      - target_label: type
        replacement: 'backend'
      - target_label: api_version
        replacement: 'v1'
    scrape_interval: 30s

  # Metric Service
  - job_name: 'metric_service'
    metrics_path: /probe
    params:
      module: [http_health_check]
    static_configs:
      - targets:
        - http://metric_service:3002/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
      - target_label: service
        replacement: 'metric_service'
      - target_label: type
        replacement: 'backend'
      - target_label: api_version
        replacement: 'v1'
    scrape_interval: 30s

  # Conversation Service V3
  - job_name: 'conversation_v3'
    metrics_path: /probe
    params:
      module: [http_health_check]
    static_configs:
      - targets:
        - http://conversation_service_v3:3008/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
      - target_label: service
        replacement: 'conversation_v3'
      - target_label: type
        replacement: 'backend'
      - target_label: api_version
        replacement: 'v3'
    scrape_interval: 30s

  # Budget Profiling Service
  - job_name: 'budget_profiling'
    metrics_path: /probe
    params:
      module: [http_health_check]
    static_configs:
      - targets:
        - http://budget_profiling_service:3006/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
      - target_label: service
        replacement: 'budget_profiling'
      - target_label: type
        replacement: 'backend'
      - target_label: api_version
        replacement: 'v1'
    scrape_interval: 30s

  # Sync Service
  - job_name: 'sync_service'
    metrics_path: /probe
    params:
      module: [http_health_check]
    static_configs:
      - targets:
        - http://sync_service:3004/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
      - target_label: service
        replacement: 'sync_service'
      - target_label: type
        replacement: 'backend'
      - target_label: api_version
        replacement: 'v1'
    scrape_interval: 30s

  # Enrichment Service
  - job_name: 'enrichment_service'
    metrics_path: /probe
    params:
      module: [http_health_check]
    static_configs:
      - targets:
        - http://enrichment_service:3005/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
      - target_label: service
        replacement: 'enrichment_service'
      - target_label: type
        replacement: 'backend'
      - target_label: api_version
        replacement: 'v1'
    scrape_interval: 30s

  # ============================================
  # INFRASTRUCTURE
  # ============================================

  # PostgreSQL (si postgres_exporter est installé)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres_exporter:9187']
  #       labels:
  #         service: 'postgresql'
  #         type: 'database'

  # Redis (si redis_exporter est installé)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis_exporter:9121']
  #       labels:
  #         service: 'redis'
  #         type: 'cache'

  # ============================================
  # NGINX
  # ============================================
  # - job_name: 'nginx'
  #   static_configs:
  #     - targets: ['nginx:9113']  # nginx-prometheus-exporter
  #       labels:
  #         service: 'nginx'
  #         type: 'proxy'
